---
- name: Clean up mock Infoblox test
  hosts: all
  gather_facts: false
  tasks:
    - name: Remove scenario artifacts
      ansible.builtin.file:
        path: "{{ molecule_ephemeral_directory }}/artifacts"
        state: absent
